#!/usr/bin/env bash
#
# STRW factory — release script
# -----------------------------------------------------------------------------
# Releases the strw-factory plugin: bumps the version in .claude-plugin/plugin.json,
# promotes the CHANGELOG "Unreleased" section, commits, tags, pushes, and creates a
# GitHub Release via the gh CLI.
#
# Run it yourself from a terminal on your own machine (git + gh handle GitHub auth):
#
#   ./scripts/release.sh patch                 # 0.1.0 -> 0.1.1
#   ./scripts/release.sh minor                 # 0.1.0 -> 0.2.0
#   ./scripts/release.sh major                 # 0.1.0 -> 1.0.0
#   ./scripts/release.sh 0.4.2                  # explicit version
#   ./scripts/release.sh patch --dry-run       # show what would happen, change nothing
#   ./scripts/release.sh setup <git-remote-url>  # one-time: init git + wire the remote
#
# Options:
#   -m, --message "text"   Release notes (overrides the CHANGELOG [Unreleased] body)
#   -n, --dry-run          Print every action, modify nothing
#       --no-push          Commit + tag locally, do not push
#       --no-gh            Skip creating the GitHub Release
#   -y, --yes              Do not prompt for confirmation
#   -h, --help             Show this help
# -----------------------------------------------------------------------------

set -euo pipefail

# ----- resolve paths ---------------------------------------------------------
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PLUGIN_DIR="$(cd "$SCRIPT_DIR/.." && pwd)"
MANIFEST="$PLUGIN_DIR/.claude-plugin/plugin.json"
CHANGELOG="$PLUGIN_DIR/CHANGELOG.md"
CONF="$SCRIPT_DIR/release.conf"

# ----- defaults (overridable via scripts/release.conf) -----------------------
MAIN_BRANCH="main"
REMOTE="origin"
USE_GH="true"
TAG_PREFIX="v"
# shellcheck disable=SC1090
[ -f "$CONF" ] && . "$CONF"

# ----- colors ----------------------------------------------------------------
if [ -t 1 ]; then
  BOLD=$(printf '\033[1m'); RED=$(printf '\033[31m'); GRN=$(printf '\033[32m')
  YEL=$(printf '\033[33m'); BLU=$(printf '\033[34m'); RST=$(printf '\033[0m')
else
  BOLD=""; RED=""; GRN=""; YEL=""; BLU=""; RST=""
fi
info()  { printf '%s\n' "${BLU}•${RST} $*"; }
ok()    { printf '%s\n' "${GRN}✓${RST} $*"; }
warn()  { printf '%s\n' "${YEL}!${RST} $*" >&2; }
die()   { printf '%s\n' "${RED}✗ $*${RST}" >&2; exit 1; }

usage() { sed -n '2,40p' "${BASH_SOURCE[0]}" | sed 's/^# \{0,1\}//'; exit 0; }

# ----- arg parsing -----------------------------------------------------------
BUMP=""; MESSAGE=""; DRY_RUN="false"; DO_PUSH="true"; CONFIRM="true"
SETUP_URL=""

while [ $# -gt 0 ]; do
  case "$1" in
    patch|minor|major) BUMP="$1"; shift ;;
    setup)             BUMP="setup"; SETUP_URL="${2:-}"; shift; [ $# -gt 0 ] && shift ;;
    [0-9]*.[0-9]*.[0-9]*) BUMP="explicit"; NEW_VERSION="$1"; shift ;;
    -m|--message)      MESSAGE="${2:-}"; shift 2 ;;
    -n|--dry-run)      DRY_RUN="true"; shift ;;
    --no-push)         DO_PUSH="false"; shift ;;
    --no-gh)           USE_GH="false"; shift ;;
    -y|--yes)          CONFIRM="false"; shift ;;
    -h|--help)         usage ;;
    *) die "Unknown argument: $1  (run with --help)" ;;
  esac
done

run() { # execute unless dry-run
  if [ "$DRY_RUN" = "true" ]; then printf '%s\n' "  ${YEL}[dry-run]${RST} $*"; else eval "$@"; fi
}

# ----- setup mode ------------------------------------------------------------
if [ "$BUMP" = "setup" ]; then
  [ -n "$SETUP_URL" ] || die "Usage: ./scripts/release.sh setup <git-remote-url>"
  cd "$PLUGIN_DIR"
  if [ ! -d .git ]; then
    info "Initializing git repository in $PLUGIN_DIR"
    git init -b "$MAIN_BRANCH"
  else
    ok "git repository already present"
  fi
  if git remote get-url "$REMOTE" >/dev/null 2>&1; then
    warn "remote '$REMOTE' already set to $(git remote get-url "$REMOTE") — leaving as is"
  else
    git remote add "$REMOTE" "$SETUP_URL"
    ok "remote '$REMOTE' -> $SETUP_URL"
  fi
  cat > "$CONF" <<EOF
# strw-factory release config (auto-generated by 'setup')
MAIN_BRANCH="$MAIN_BRANCH"
REMOTE="$REMOTE"
USE_GH="$USE_GH"
TAG_PREFIX="$TAG_PREFIX"
EOF
  ok "wrote $CONF"
  info "Next: commit your files and run  ./scripts/release.sh <patch|minor|major>"
  exit 0
fi

[ -n "$BUMP" ] || die "Specify a bump: patch | minor | major | X.Y.Z  (or 'setup <url>'). See --help."

# ----- preconditions ---------------------------------------------------------
command -v git >/dev/null 2>&1 || die "git not found on PATH"
[ -f "$MANIFEST" ] || die "manifest not found: $MANIFEST"
cd "$PLUGIN_DIR"
git rev-parse --is-inside-work-tree >/dev/null 2>&1 \
  || die "$PLUGIN_DIR is not a git repo. Run:  ./scripts/release.sh setup <git-remote-url>"

if [ "$USE_GH" = "true" ]; then
  command -v gh >/dev/null 2>&1 || die "gh CLI not found. Install it or run with --no-gh."
  gh auth status >/dev/null 2>&1 || die "gh is not authenticated. Run 'gh auth login' or use --no-gh."
fi

# clean working tree
if [ "$DRY_RUN" = "false" ] && [ -n "$(git status --porcelain)" ]; then
  die "Working tree is dirty. Commit or stash changes before releasing."
fi

# on the right branch
CUR_BRANCH="$(git rev-parse --abbrev-ref HEAD)"
if [ "$CUR_BRANCH" != "$MAIN_BRANCH" ]; then
  warn "You are on '$CUR_BRANCH', not '$MAIN_BRANCH'."
  [ "$CONFIRM" = "true" ] && { printf 'Continue anyway? [y/N] '; read -r a; [ "$a" = "y" ] || die "Aborted."; }
fi

# ----- current + next version ------------------------------------------------
CUR_VERSION="$(grep -Eo '"version"[[:space:]]*:[[:space:]]*"[0-9]+\.[0-9]+\.[0-9]+"' "$MANIFEST" \
  | grep -Eo '[0-9]+\.[0-9]+\.[0-9]+' | head -1)"
[ -n "$CUR_VERSION" ] || die "Could not read current version from $MANIFEST"

IFS=. read -r MA MI PA <<EOF
$CUR_VERSION
EOF
case "$BUMP" in
  patch) NEW_VERSION="$MA.$MI.$((PA+1))" ;;
  minor) NEW_VERSION="$MA.$((MI+1)).0" ;;
  major) NEW_VERSION="$((MA+1)).0.0" ;;
  explicit) : ;;  # NEW_VERSION already set
esac
echo "$NEW_VERSION" | grep -Eq '^[0-9]+\.[0-9]+\.[0-9]+$' || die "Invalid target version: $NEW_VERSION"

# ensure strictly newer (numeric compare)
ver_num() { IFS=. read -r a b c <<EOF
$1
EOF
printf '%d%03d%03d' "$a" "$b" "$c"; }
[ "$(ver_num "$NEW_VERSION")" -gt "$(ver_num "$CUR_VERSION")" ] \
  || die "Target $NEW_VERSION is not greater than current $CUR_VERSION"

TAG="${TAG_PREFIX}${NEW_VERSION}"
git rev-parse -q --verify "refs/tags/$TAG" >/dev/null && die "Tag $TAG already exists."

DATE="$(date +%Y-%m-%d)"
info "${BOLD}Release $CUR_VERSION → $NEW_VERSION${RST}  (tag $TAG, $DATE)"

# ----- release notes ---------------------------------------------------------
# Priority: -m message > CHANGELOG [Unreleased] body > placeholder
NOTES_FILE="$(mktemp)"; trap 'rm -f "$NOTES_FILE"' EXIT
if [ -n "$MESSAGE" ]; then
  printf '%s\n' "$MESSAGE" > "$NOTES_FILE"
elif [ -f "$CHANGELOG" ] && grep -q '## \[Unreleased\]' "$CHANGELOG"; then
  awk '/## \[Unreleased\]/{f=1;next} /^## \[/{f=0} f' "$CHANGELOG" \
    | grep -vE '^[[:space:]]*(<!--|-->)' \
    | sed '/^[[:space:]]*$/d' > "$NOTES_FILE"
fi
[ -s "$NOTES_FILE" ] || printf '%s\n' "- Release $NEW_VERSION" > "$NOTES_FILE"

# ----- confirm ---------------------------------------------------------------
echo; echo "${BOLD}Release notes:${RST}"; sed 's/^/    /' "$NOTES_FILE"; echo
if [ "$CONFIRM" = "true" ] && [ "$DRY_RUN" = "false" ]; then
  printf 'Proceed with release %s? [y/N] ' "$TAG"; read -r a; [ "$a" = "y" ] || die "Aborted."
fi

# ----- 1) bump plugin.json ---------------------------------------------------
info "Updating $MANIFEST"
if [ "$DRY_RUN" = "false" ]; then
  tmp="$(mktemp)"
  sed -E 's/("version"[[:space:]]*:[[:space:]]*")[0-9]+\.[0-9]+\.[0-9]+(")/\1'"$NEW_VERSION"'\2/' \
    "$MANIFEST" > "$tmp" && mv "$tmp" "$MANIFEST"
  grep -q "\"version\": \"$NEW_VERSION\"" "$MANIFEST" || die "Version rewrite failed in $MANIFEST"
fi

# ----- 1b) sync version in marketplace.json (if present) ---------------------
MARKETPLACE="$PLUGIN_DIR/.claude-plugin/marketplace.json"
if [ -f "$MARKETPLACE" ]; then
  info "Updating $MARKETPLACE"
  if [ "$DRY_RUN" = "false" ]; then
    tmp="$(mktemp)"
    # update only the first "version" after the "plugins" array (the plugin's version),
    # leaving metadata.version untouched
    awk -v new="$NEW_VERSION" '
      /"plugins"[[:space:]]*:/ { inp=1 }
      inp && !done && /"version"[[:space:]]*:/ {
        sub(/"version"[[:space:]]*:[[:space:]]*"[0-9]+\.[0-9]+\.[0-9]+"/, "\"version\": \"" new "\"")
        done=1
      }
      { print }
    ' "$MARKETPLACE" > "$tmp" && mv "$tmp" "$MARKETPLACE"
  fi
fi

# ----- 2) update CHANGELOG ---------------------------------------------------
info "Updating $CHANGELOG"
if [ "$DRY_RUN" = "false" ] && [ -f "$CHANGELOG" ]; then
  tmp="$(mktemp)"
  if grep -q '## \[Unreleased\]' "$CHANGELOG"; then
    # rename the Unreleased heading to the new version, and add a fresh empty Unreleased
    sed -E "s/^## \[Unreleased\].*/## [Unreleased]\n\n## [$NEW_VERSION] — $DATE/" \
      "$CHANGELOG" > "$tmp" && mv "$tmp" "$CHANGELOG"
  else
    # insert a new section right after the top-level title
    awk -v v="$NEW_VERSION" -v d="$DATE" '
      NR==1{print; print ""; print "## [Unreleased]"; print ""; print "## [" v "] — " d; next}
      {print}' "$CHANGELOG" > "$tmp" && mv "$tmp" "$CHANGELOG"
  fi
fi

# ----- 3) commit, tag, push --------------------------------------------------
info "Committing"
run "git add -A"
run "git commit -m 'chore(release): $TAG'"
info "Tagging $TAG"
run "git tag -a '$TAG' -m 'strw-factory $TAG'"

if [ "$DO_PUSH" = "true" ]; then
  info "Pushing to $REMOTE $MAIN_BRANCH + tags"
  run "git push $REMOTE HEAD:$MAIN_BRANCH"
  run "git push $REMOTE '$TAG'"
else
  warn "--no-push set: not pushing. Later run: git push $REMOTE HEAD:$MAIN_BRANCH && git push $REMOTE $TAG"
fi

# ----- 4) GitHub Release -----------------------------------------------------
if [ "$USE_GH" = "true" ] && [ "$DO_PUSH" = "true" ]; then
  info "Creating GitHub Release $TAG"
  run "gh release create '$TAG' --title 'strw-factory $TAG' --notes-file '$NOTES_FILE'"
elif [ "$USE_GH" = "true" ]; then
  warn "Skipping gh release because --no-push was set (nothing on remote to attach to)."
fi

echo
if [ "$DRY_RUN" = "true" ]; then
  ok "Dry run complete — no changes made. Version would go $CUR_VERSION → $NEW_VERSION ($TAG)."
else
  ok "Released ${BOLD}$TAG${RST}."
fi
